export const rawBookings = [
    {
      id: "B-4001",
      guestName: "Alice Monroe",
      roomId: "dv-101",
      roomType: "Deluxe Villa",
      roomNumber: "101",
      guests: 2,
      phone: "555-1234",
      email: "alice@example.com",
      idType: "Passport",
      idNumber: "X1234567",
      checkIn: new Date(2025, 3, 16, 9, 0),
      checkOut: new Date(2025, 3, 18, 11, 0),
      status: "in-house",
      amount: "$950.00",
      source: "Expedia",
      channelId: "EXP-44566",
      expenses: [
        { description: "Room Service", amount: 45 },
        { description: "Mini Bar", amount: 20 },
      ],
      revisions: [
        { date: new Date(2025, 3, 15), description: "Extended by 1 night" },
      ],
      notes: [
        {
          author: "Front Desk",
          content: "Prefers extra pillows.",
          createdAt: new Date(2025, 3, 15, 14, 30),
        },
      ],
    },
    {
      id: "B-4002",
      guestName: "Brandon Lee",
      roomId: "dv-102",
      roomType: "Deluxe Villa",
      roomNumber: "102",
      guests: 1,
      phone: "555-5678",
      email: "brandon@example.com",
      idType: "Driver's License",
      idNumber: "DL9876543",
      checkIn: new Date(2025, 3, 18, 14, 0),
      checkOut: new Date(2025, 3, 19, 12, 0),
      status: "departure",
      amount: "$400.00",
      source: "Direct",
      channelId: "DIR-90807",
      expenses: [{ description: "Laundry", amount: 30 }],
      revisions: [],
      notes: [],
    },
    {
      id: "B-4003",
      guestName: "Clara Wu",
      roomId: "dv-103",
      roomType: "Deluxe Villa",
      roomNumber: "103",
      guests: 3,
      phone: "555-8765",
      email: "clara@example.com",
      idType: "National ID",
      idNumber: "NID54321",
      checkIn: new Date(2025, 3, 19, 10, 30),
      checkOut: new Date(2025, 3, 20, 12, 0),
      status: "arrival",
      amount: "$380.00",
      source: "Agoda",
      channelId: "AGO-10101",
      expenses: [],
      revisions: [],
      notes: [
        {
          author: "Admin",
          content: "Requested early check-in.",
          createdAt: new Date(2025, 3, 18, 11, 45),
        },
      ],
    },
    {
      id: "B-4004",
      guestName: "David Jones",
      roomId: "sr-201",
      roomType: "Standard Room",
      roomNumber: "201",
      guests: 2,
      phone: "555-2345",
      email: "david@example.com",
      idType: "Passport",
      idNumber: "P1029384",
      checkIn: new Date(2025, 3, 20, 8, 0),
      checkOut: new Date(2025, 3, 22, 10, 0),
      status: "tentative",
      amount: "$270.00",
      source: "Call",
      channelId: "CALL-4455",
      expenses: [],
      revisions: [],
      notes: [],
    },
    {
      id: "B-4005",
      guestName: "Evelyn Clark",
      roomId: "sr-202",
      roomType: "Standard Room",
      roomNumber: "202",
      guests: 1,
      phone: "555-6789",
      email: "evelyn@example.com",
      idType: "Driver's License",
      idNumber: "DL444555",
      checkIn: new Date(2025, 3, 21, 13, 30),
      checkOut: new Date(2025, 3, 23, 11, 0),
      status: "dnr",
      amount: "$190.00",
      source: "Phone",
      channelId: "PHN-2233",
      expenses: [{ description: "Airport Pickup", amount: 60 }],
      revisions: [],
      notes: [],
    },
    {
      id: "B-4006",
      guestName: "Georgia King",
      roomId: "sr-204",
      roomType: "Standard Room",
      roomNumber: "204",
      guests: 2,
      phone: "555-9999",
      email: "georgia@example.com",
      idType: "Passport",
      idNumber: "X9876543",
      checkIn: new Date(2025, 3, 17, 16, 0),
      checkOut: new Date(2025, 3, 18, 10, 0),
      status: "no-show",
      amount: "$300.00",
      source: "OTA",
      channelId: "OTA-90876",
      expenses: [],
      revisions: [],
      notes: [],
    },
    {
      id: "B-4007",
      guestName: "Jessica Miller",
      roomId: "sr-203",
      roomType: "Standard Room",
      roomNumber: "203",
      guests: 1,
      phone: "555-7890",
      email: "jessica@example.com",
      idType: "Passport",
      idNumber: "P565656",
      checkIn: new Date(2025, 3, 16, 9, 0),
      checkOut: new Date(2025, 3, 16, 11, 0),
      status: "checked out",
      amount: "$200.00",
      source: "Direct",
      channelId: "DIR-22334",
      expenses: [],
      revisions: [],
      notes: [],
    },
    {
      id: "B-4008",
      guestName: "Henry Lee",
      roomId: "s-301",
      roomType: "Suite",
      roomNumber: "301",
      guests: 1,
      phone: "555-0001",
      email: "henry@example.com",
      idType: "Passport",
      idNumber: "P3216549",
      checkIn: new Date(2025, 3, 15, 7, 30),
      checkOut: new Date(2025, 3, 16, 12, 0),
      status: "confirmed",
      amount: "$720.00",
      source: "Website",
      channelId: "WEB-00088",
      expenses: [{ description: "Room Upgrade", amount: 100 }],
      revisions: [],
      notes: [],
    },
    {
      id: "B-4009",
      guestName: "Irene Smith",
      roomId: "s-302",
      roomType: "Suite",
      roomNumber: "302",
      guests: 3,
      phone: "555-4433",
      email: "irene@example.com",
      idType: "National ID",
      idNumber: "NID112233",
      checkIn: new Date(2025, 3, 22, 15, 15),
      checkOut: new Date(2025, 3, 24, 12, 0),
      status: "confirmed",
      amount: "$850.00",
      source: "Website",
      channelId: "WEB-00991",
      expenses: [],
      revisions: [],
      notes: [],
    }
  ];